/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;

/**
 *
 * @author D diviaruna
 */
public class MainJFrame extends javax.swing.JFrame {


    /**
     * Creates new form MainJFrame
     */
    private VitalSignHistory vsh; 
    public MainJFrame() {
        initComponents();
        vsh = new VitalSignHistory();
        maxBPTextField.setText(Double.toString(120));
        minBPTextField.setText(Double.toString(80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        leftjPanel = new javax.swing.JPanel();
        CreateBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        maxBPjLabel = new javax.swing.JLabel();
        minBPjLabel = new javax.swing.JLabel();
        maxBPTextField = new javax.swing.JTextField();
        minBPTextField = new javax.swing.JTextField();
        abnormaljButton = new javax.swing.JButton();
        rightjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        SplitPane.setPreferredSize(new java.awt.Dimension(700, 500));

        CreateBtn.setText("Create Vital Sign");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });

        ViewBtn.setText("View Vital Signs");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        maxBPjLabel.setText("MAX_BP");

        minBPjLabel.setText("MIN_BP");

        maxBPTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxBPTextFieldActionPerformed(evt);
            }
        });

        abnormaljButton.setText("Abnormal");
        abnormaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abnormaljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftjPanelLayout = new javax.swing.GroupLayout(leftjPanel);
        leftjPanel.setLayout(leftjPanelLayout);
        leftjPanelLayout.setHorizontalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minBPjLabel)
                            .addComponent(maxBPjLabel)))
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minBPTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(maxBPTextField)))
                    .addGroup(leftjPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(abnormaljButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(ViewBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CreateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftjPanelLayout.setVerticalGroup(
            leftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(CreateBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewBtn)
                .addGap(18, 18, 18)
                .addComponent(maxBPjLabel)
                .addGap(18, 18, 18)
                .addComponent(maxBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(minBPjLabel)
                .addGap(18, 18, 18)
                .addComponent(minBPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(abnormaljButton)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(leftjPanel);

        javax.swing.GroupLayout rightjPanelLayout = new javax.swing.GroupLayout(rightjPanel);
        rightjPanel.setLayout(rightjPanelLayout);
        rightjPanelLayout.setHorizontalGroup(
            rightjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        rightjPanelLayout.setVerticalGroup(
            rightjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(rightjPanel);

        getContentPane().add(SplitPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        ViewVitalsJPanel viewJPanel = new ViewVitalsJPanel(vsh);
        SplitPane.setRightComponent(viewJPanel);
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        CreateVitalsJPanel createJPanel = new CreateVitalsJPanel(vsh);
        SplitPane.setRightComponent(createJPanel);
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void abnormaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abnormaljButtonActionPerformed
        // TODO add your handling code here:
        double MAX_BP = Double.parseDouble(maxBPTextField.getText());
        double MIN_BP = Double.parseDouble(minBPTextField.getText());
        
        AbnormalJPanel abnormalJPanel = new AbnormalJPanel(vsh,MAX_BP,MIN_BP);
        SplitPane.setRightComponent(abnormalJPanel);

    }//GEN-LAST:event_abnormaljButtonActionPerformed

    private void maxBPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxBPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxBPTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBtn;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton abnormaljButton;
    private javax.swing.JPanel leftjPanel;
    private javax.swing.JTextField maxBPTextField;
    private javax.swing.JLabel maxBPjLabel;
    private javax.swing.JTextField minBPTextField;
    private javax.swing.JLabel minBPjLabel;
    private javax.swing.JPanel rightjPanel;
    // End of variables declaration//GEN-END:variables
}
