/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D diviaruna
 */
public class ViewVitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalsJPanel
     */private VitalSignHistory vsh;
    public ViewVitalsJPanel(VitalSignHistory vsh) {
        initComponents();
        this.vsh=vsh;
        populateTable();
    }
public void populateTable(){
    DefaultTableModel dtm = (DefaultTableModel)VitalSignsjTable.getModel();
    dtm.setRowCount(0);
    for(VitalSigns vs : vsh.getVitalSignHistory()){
        Object row[]= new Object[2];
        row[0]=vs;
        row[1]=vs.getBloodPressure();
        dtm.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewVitalSignsjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignsjTable = new javax.swing.JTable();
        viewDetailsjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        pulsejLabel = new javax.swing.JLabel();
        datejLabel = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        pulseTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        tempjLabel = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        bloodPessurejLabel = new javax.swing.JLabel();
        updatejButton = new javax.swing.JButton();
        confirmjButton = new javax.swing.JButton();

        setEnabled(false);

        viewVitalSignsjLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        viewVitalSignsjLabel.setForeground(new java.awt.Color(0, 51, 204));
        viewVitalSignsjLabel.setText("View Vital Signs");

        VitalSignsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(VitalSignsjTable);

        viewDetailsjButton.setText("View Details");
        viewDetailsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsjButtonActionPerformed(evt);
            }
        });

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        pulsejLabel.setText("Pulse");

        datejLabel.setText("Date");

        bloodPressureTextField.setEnabled(false);
        bloodPressureTextField.setOpaque(false);

        pulseTextField.setEnabled(false);
        pulseTextField.setOpaque(false);

        dateTextField.setEnabled(false);
        dateTextField.setOpaque(false);

        tempjLabel.setText("Temeperature");

        temperatureTextField.setEnabled(false);
        temperatureTextField.setOpaque(false);

        bloodPessurejLabel.setText("Blood Pressure");

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        confirmjButton.setText("Confirm");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(viewVitalSignsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewDetailsjButton)
                            .addGap(46, 46, 46)
                            .addComponent(updatejButton)
                            .addGap(39, 39, 39)
                            .addComponent(deletejButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tempjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bloodPessurejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pulsejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(datejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmjButton)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(viewVitalSignsjLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailsjButton)
                    .addComponent(deletejButton)
                    .addComponent(updatejButton))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPessurejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmjButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsjButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = VitalSignsjTable.getSelectedRow();
        if(selectedrow>=0)
        {
          VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);
          temperatureTextField.setText(String.valueOf(vs.getTemperature()));
          bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
          pulseTextField.setText(String.valueOf(vs.getPulse()));
          dateTextField.setText(vs.getDate());
        
        }
        else
            JOptionPane.showMessageDialog(null,"Select any row");
    }//GEN-LAST:event_viewDetailsjButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = VitalSignsjTable.getSelectedRow();
        if(selectedrow>=0)
        {
           VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);
           vsh.deleteVitals(vs);
           JOptionPane.showMessageDialog(null,"Vital Sign has been deleted");
           populateTable();

        }
        else
            JOptionPane.showMessageDialog(null,"Select any row");
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
                int selectedrow = VitalSignsjTable.getSelectedRow();
                if(selectedrow>=0)
        {
            
            temperatureTextField.setEnabled(true);
            bloodPressureTextField.setEnabled(true);
            pulseTextField.setEnabled(true);
            dateTextField.setEnabled(true);

            
           VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);

          temperatureTextField.setText(String.valueOf(vs.getTemperature()));
          bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
          pulseTextField.setText(String.valueOf(vs.getPulse()));
          dateTextField.setText(vs.getDate());
          
          populateTable();
        
        }else{
                    JOptionPane.showMessageDialog(null, "Select a row");
                }

    }//GEN-LAST:event_updatejButtonActionPerformed
    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        int selectedrow = VitalSignsjTable.getSelectedRow();
                if(selectedrow>=0)
        {
            
            temperatureTextField.setEnabled(true);
            bloodPressureTextField.setEnabled(true);
            pulseTextField.setEnabled(true);
            dateTextField.setEnabled(true);

            
           VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);

          vs.setTemperature(Double.parseDouble(temperatureTextField.getText()));
          vs.setBloodPressure(Double.parseDouble(bloodPressureTextField.getText()));
          vs.setPulse(Integer.parseInt(pulseTextField.getText()));
          vs.setDate(dateTextField.getText());
          
          populateTable();
            temperatureTextField.setEnabled(false);
            bloodPressureTextField.setEnabled(false);
            pulseTextField.setEnabled(false);
            dateTextField.setEnabled(false);
          
        
        }else{
                    JOptionPane.showMessageDialog(null, "Select a row");
                }
    }//GEN-LAST:event_confirmjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VitalSignsjTable;
    private javax.swing.JLabel bloodPessurejLabel;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JButton deletejButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JLabel pulsejLabel;
    private javax.swing.JTextField temperatureTextField;
    private javax.swing.JLabel tempjLabel;
    private javax.swing.JButton updatejButton;
    private javax.swing.JButton viewDetailsjButton;
    private javax.swing.JLabel viewVitalSignsjLabel;
    // End of variables declaration//GEN-END:variables
}
