/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import Business.VitalSigns;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D diviaruna
 */
public class AbnormalJPanel extends javax.swing.JPanel {

    private VitalSignHistory vsh;
    private double MAX_BP;
    private double MIN_BP;
    
    public AbnormalJPanel(VitalSignHistory vsh, double MAX_BP,double MIN_BP) {
        initComponents();
        this.vsh=vsh;
        this.MAX_BP=MAX_BP;
        this.MIN_BP=MIN_BP;
        populateTable();
        setAllEnabled(false);
      
    }
        private void setAllEnabled(boolean b){
        temperatureTextField.setEnabled(b);
        bloodPressureTextField.setEnabled(b);
        pulseTextField.setEnabled(b);
        dateTextField.setEnabled(b);
        }
    public void populateTable(){
    DefaultTableModel dtm = (DefaultTableModel)VitalSignsjTable.getModel();
    dtm.setRowCount(0);
    for(VitalSigns vs : vsh.getVitalSignHistory()){
        Object row[]= new Object[2];
        row[0]=vs;
        row[1]=vs.getBloodPressure();
        if(Double.parseDouble(row[1].toString())< this.MIN_BP || Double.parseDouble(row[1].toString()) > this.MAX_BP)
        dtm.addRow(row);
        
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignsjTable = new javax.swing.JTable();
        viewDetailsjButton = new javax.swing.JButton();
        deletejButton = new javax.swing.JButton();
        tempjLabel = new javax.swing.JLabel();
        temperatureTextField = new javax.swing.JTextField();
        bloodPessurejLabel = new javax.swing.JLabel();
        bloodPressureTextField = new javax.swing.JTextField();
        pulsejLabel = new javax.swing.JLabel();
        pulseTextField = new javax.swing.JTextField();
        datejLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        abnormalJLabel = new javax.swing.JLabel();
        confirmjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        VitalSignsjTable.setBackground(new java.awt.Color(255, 0, 51));
        VitalSignsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Blood Pressure"
            }
        ));
        jScrollPane1.setViewportView(VitalSignsjTable);

        viewDetailsjButton.setText("View Details");
        viewDetailsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsjButtonActionPerformed(evt);
            }
        });

        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        tempjLabel.setText("Temeperature");

        temperatureTextField.setEnabled(false);
        temperatureTextField.setOpaque(false);

        bloodPessurejLabel.setText("Blood Pressure");

        bloodPressureTextField.setEnabled(false);
        bloodPressureTextField.setOpaque(false);

        pulsejLabel.setText("Pulse");

        pulseTextField.setEnabled(false);
        pulseTextField.setOpaque(false);

        datejLabel.setText("Date");

        dateTextField.setEnabled(false);
        dateTextField.setOpaque(false);

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        abnormalJLabel.setBackground(new java.awt.Color(0, 102, 255));
        abnormalJLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        abnormalJLabel.setForeground(new java.awt.Color(0, 51, 204));
        abnormalJLabel.setText("Abnormal Vital Sign ");

        confirmjButton.setText("Confirm");
        confirmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(viewDetailsjButton)
                        .addGap(34, 34, 34)
                        .addComponent(updatejButton)
                        .addGap(36, 36, 36)
                        .addComponent(deletejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(abnormalJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodPessurejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulsejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmjButton))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(abnormalJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletejButton)
                    .addComponent(viewDetailsjButton)
                    .addComponent(updatejButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodPessurejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodPressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulsejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmjButton)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsjButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = VitalSignsjTable.getSelectedRow();
        if(selectedrow>=0)
        {
            VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);
            temperatureTextField.setText(String.valueOf(vs.getTemperature()));
            bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());
            
        setAllEnabled(false);


        }
        else
        JOptionPane.showMessageDialog(null,"Select any row");
    }//GEN-LAST:event_viewDetailsjButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = VitalSignsjTable.getSelectedRow();
        if(selectedrow>=0)
        {
            VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);
            vsh.deleteVitals(vs);
            JOptionPane.showMessageDialog(null,"Vital Sign has been deleted");
            populateTable();

        }
        else
        JOptionPane.showMessageDialog(null,"Select any row");
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        int selectedrow = VitalSignsjTable.getSelectedRow();
        if(selectedrow>=0)
        {

        setAllEnabled(true);


            VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);

            temperatureTextField.setText(String.valueOf(vs.getTemperature()));
            bloodPressureTextField.setText(String.valueOf(vs.getBloodPressure()));
            pulseTextField.setText(String.valueOf(vs.getPulse()));
            dateTextField.setText(vs.getDate());

            populateTable();

        }else{
            JOptionPane.showMessageDialog(null, "Select a row");
        }
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void confirmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmjButtonActionPerformed
        // TODO add your handling code here:
        int selectedrow = VitalSignsjTable.getSelectedRow();
                if(selectedrow>=0)
        {
            
        setAllEnabled(true);

            
          VitalSigns vs = (VitalSigns)VitalSignsjTable.getValueAt(selectedrow, 0);
          vs.setTemperature(Double.parseDouble(temperatureTextField.getText()));
          vs.setBloodPressure(Double.parseDouble(bloodPressureTextField.getText()));
          vs.setPulse(Integer.parseInt(pulseTextField.getText()));
          vs.setDate(dateTextField.getText());
          
          populateTable();
        setAllEnabled(false);

          
        
        }else{
                    JOptionPane.showMessageDialog(null, "Select a row");
                }
                                  
    }//GEN-LAST:event_confirmjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VitalSignsjTable;
    private javax.swing.JLabel abnormalJLabel;
    private javax.swing.JLabel bloodPessurejLabel;
    private javax.swing.JTextField bloodPressureTextField;
    private javax.swing.JButton confirmjButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JButton deletejButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pulseTextField;
    private javax.swing.JLabel pulsejLabel;
    private javax.swing.JTextField temperatureTextField;
    private javax.swing.JLabel tempjLabel;
    private javax.swing.JButton updatejButton;
    private javax.swing.JButton viewDetailsjButton;
    // End of variables declaration//GEN-END:variables
}
